version: '3.8'

services:
  web:
    build:
      context: .
      args:
        VITE_API_BASE_URL: https://localhost:7268 # docker compose.yml
    ports:
      - "5173:5173" # Vite dev server
    environment:
      - NODE_ENV=production
    networks:
      - smart-meter-network

volumes:
  node_modules:

networks:
  smart-meter-network:
    driver: bridge
  

