services:
  frontend:
    image: ghcr.io/illuminat3/smart-meter-system-frontend:latest
    container_name: frontend
    environment:
      VITE_PREVIEW_PORT: 4173
      VITE_API_BASE_URL: http://host.docker.internal:5234
    ports:
      - "4173:4173"
