# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  meterapi:
    image: meterapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5234:5234
