name: Meter Agent PR Build

on:
  pull_request:
    paths:
      - 'meter-agent/**'
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build Meter Agent PRs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./meter-agent/meter-agent

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./meter-agent/meter-agent

    - name: Test
      run: dotnet test --no-build --configuration Release
      working-directory: ./meter-agent
