name: Mock Database Build PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'mock-database/**'
  push:
    paths:
      - 'mock-database/**'

permissions:
  contents: read

jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: mock-database
          file: mock-database/Dockerfile
          push: false
